name: Sync Code to Server on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key and known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Sync code to server using rsync
        run: |
          rsync -avz --delete -e "ssh -i ~/.ssh/id_rsa" ./ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/root/testsite
